# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Biogafia"
  url = "#about"
  weight = 1

[[main]]
  name = "Abilità"
  url = "#abilita"
  weight = 2

[[main]]
  name = "Divulgazione"
  url = "#talks"
  weight = 3

[[main]]
  name = "Pubblicazioni"
  url = "#publications"
  weight = 4

[[main]]
  name = "Esperienze"
  url = "#experience"
  weight = 5

[[main]]
  name = "Certificazioni"
  url = "#accomplishments"
  weight = 6

[[main]]
  name = "Progetti"
  url = "#projects"
  weight = 7

[[main]]
  name = "Contatti"
  url = "#contact"
  weight = 8

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 [[main]]
    name = "CV"
    url = "files/cv.pdf"
    weight = 9
